### ISSUE TITLE
Desyncronized data.

### ISSUE THREAD

**Issue by 22kHz** [timothyrichards/albion_shopper#3]
Pls add date of updating data from dataproject onto the bottom of each column. It is bad when you see 2 days old data on the spreadsheet. Btw great service, i wish you good luck!

**Comment by timothyrichards** [comment]
Great suggestion will do!

**Comment by timothyrichards** [comment]
Please review and let me know what you think @22kHz

**Comment by 22kHz** [comment]
Awesome!
