### ISSUE TITLE
Price history

### ISSUE THREAD

**Issue by 22kHz** [timothyrichards/albion_shopper#4]
Pls find out some way of making black market (all other markets, BM is the most important) 4 Weeks chart same as ingame, using AO data project data. This required to compare current prices with Avg price on black market.

**Comment by timothyrichards** [comment]
I'll look into this and see what I can do, I'm unsure if I can get the data that I would need to generate this from the API or if I would have to start storing data on my own.

**Comment by 22kHz** [comment]
Please, look forward onto new API from Data project. You can get for example t4 bags price history like that 
curl
https://www.albion-online-data.com/api/v2/stats/history/T4_BAG?time-scale=24&date=2-22-2020
I think you can add new list with date and put today's day value by-default.

**Comment by timothyrichards** [comment]
Hey @22kHz this feature is now live on the site

**Comment by 22kHz** [comment]
@timothyrichards It seems this feature isn't working in a correct way. The way you'r showing data as a graphic is amazing. The data doesn't update each time when you'r open it, just printing data at the end of graph again.

**Comment by 22kHz** [comment]
@timothyrichards Do you have a discord? I want to support future development of your tool with some silver in-game.

**Comment by timothyrichards** [comment]
Good catch on the bug, I'll fix that when I have time to

I don't have a server but I do have an account, you can add me: ScarletPaladin#0001

I also stream on https://www.twitch.tv/scarletpaladin :)
